# This configuration file is used on the workflows/pr.yml
# It configures the add-reviewers-and-assignee job, which adds reviewers and assignees to pull requests.
# This makes it easier to visualize who is responsible for reviewing and merging the pull request
# and also helps to manage the workload of the team.

addReviewers: true

# The author of the PR is assigned to it
addAssignees: author

# The admin team group is added as reviewer
reviewers:
  - vtex/admin
