kind: pipeline
type: kubernetes
name: Pullrequest
steps:
  - name: Dependencies
    image: node:14.17.0
    pull: if-not-exists
    resources: 
      limits:
        cpu: 2000
        memory: 4Gi
    commands:
      - yarn install
  - name: Build
    image: node:14.17.0
    pull: if-not-exists
    resources: 
      limits:
        cpu: 2000
        memory: 4Gi
    commands:
      - yarn build:ci
    depends_on:
      - Dependencies
  - name: Unit Tests
    image: node:14.17.0
    pull: if-not-exists
    resources: 
      limits:
        cpu: 2000
        memory: 4Gi
    commands:
      - yarn test:ci
    depends_on:
      - Build
trigger:
  event:
    - pull_request
