# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  chromatic-deployment:
    docker:
      - image: circleci/node:16

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install
      - run: yarn build
      - run: yarn chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --skip 'dependabot/**'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build:
    docker:
      - image: circleci/node:16

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install
      - run: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:16

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install
      - run: yarn build
      - run: yarn test:ci

  publish:
    docker:
      - image: circleci/node:16

    working_directory: ~/repo

    steps:
      - checkout
      - when:
          condition:
            equal: [feat/publish-workflow, << pipeline.git.branch >>]

          steps:
            - run: yarn install
            - run: yarn build
            - run: yarn publish:test

workflows:
  version: 2

  chromatic-deploy:
    jobs:
      - chromatic-deployment

  build_and_test:
    jobs:
      - build
      - test:
          name: '@vtex/admin-ui test'
          requires:
            - build

  publish:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - feat/publish-workflow
