name: Bug Report
description: Report a problem with Shoreline
labels: ['bug', 'status: pending']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe the problem and explain the current behavior. If applicable, add screenshots/videos to help explain the problem.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: input
    id: reproducible-example
    attributes:
      label: Reproducible Example
      description: Provide a reduced test case with the [Shoreline sandbox template](https://codesandbox.io/p/sandbox/shoreline-react-vg67lx).
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: Describe how could the bug could be solved or what changes would need to be made. Provide the links, for example from a Figma file or a CodeSandbox, or code snippets that apply to your solution.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: dropdown
    id: package
    attributes:
      label: Package
      multiple: true
      options:
        - '@vtex/shoreline'
        - '@vtex/shoreline-ts-table'
        - '@vtex/shoreline-stylelint'
        - '@vtex/shoreline-icons'
  - type: textarea
    id: packages-version
    attributes:
      label: Packages version
  - type: input
    id: browser
    attributes:
      label: Browser
  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      options:
        – - 
        - pnpm
        - npm
        - yarn
        - bun
      default: -
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report ✨
