name: Bug Report
description: Report a problem with Shoreline
labels: ['bug', 'status: pending']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report ✨
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a short description of the problem.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: What happens instead of the expected behavior? If applicable, add screenshots/videos to help explain the problem.
      value: |
        Wrap animated gifs/videos in a details tag:
        <details>
          <summary>Summary of your gif(s)</summary>
          <img src="..." alt="Description of what the gif shows">
        </details>
  - type: input
    id: reproducible-example
    attributes:
      label: Reproducible Example
      description: Provide a reduced test case with the [Shoreline sandbox template]().
      value: |
        [Link to sandbox]()
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: How could we solve this bug? What changes would need to made?
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package(s) are you using?
      multiple: true
      options:
        - '@vtex/shoreline'
        - '@vtex/shoreline-primitives'
        - '@vtex/shoreline-ts-table'
        - '@vtex/shoreline-stylelint'
        - '@vtex/shoreline-codemod'
        - '@vtex/shoreline-icons'
  - type: input
    id: shoreline-package-version
    attributes:
      label: Shoreline package version
  - type: input
    id: browser
    attributes:
      label: Browser
  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      options:
        - pnpm
        - npm
        - yarn
      default: 0
    validations:
      required: true
