name: Pull Request workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  # this job uses the configuration file in .github/auto_assign.yml
  add-assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
  comment_pr:
    runs-on: ubuntu-latest
    name: Ask to set GitHub projects fields and labels to PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hi @${{ github.actor }}! Thanks for opening this PR. Please set the Shoreline projects fields and labels to this PR to improve our workflow. You can do this by clicking the gear icon on the right side of the PR page and then clicking on the "Projects" tab.
