name: Pull Request workflow

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  build:
    name: Build and test all packages
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'edited' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 25

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Code lint
        run: pnpm lint

      - name: Stylelint
        run: pnpm stylelint **/*.css

      - name: Test
        run: pnpm test:ci

      - name: Test Storybook
        run: pnpm test:storybook:ci

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build:storybook:ci
          exitOnceUploaded: true
          exitZeroOnChanges: true

  semantic-pr:
    name: Validate PR title for semantic versioning
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
